version: "3.2"
services:
  nodejs:
    build:
      context: .
    image: ashanust/movie-metadata-management
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
    environment:
      - DB_HOST=movie-metadata-management-sql-app
      - DB_USER=ashan
      - DB_PASS=root
      - DB_SCHEME=axinoms
      - DB_PORT=3306
      - SERVER_PORT=5000
      - AUTH0_AUDIENCE=https://ashan-movie-api.axinom.com
      - AUTH0_DOMAIN=ashan-movie.us.auth0.com
      - JWT_SECRET=User123
      - TOKEN_EXPIRE=1h
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "5000:5000"
    container_name: movie-metadata-management-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=ashan
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=axinoms
    container_name: movie-metadata-management-sql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "5001:80"
    environment:
      - PMA_HOST=movie-metadata-management-sql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: movie-metadata-management-phpmyadmin-app
networks:
  frontend:
  backend: